# Week 4: Regression Models

## Task 1: California Housing Price Prediction

In [95]:
import pandas as pd

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [96]:
housing = fetch_california_housing()

In [97]:
df = pd.DataFrame(
    housing.data,
    columns=housing.feature_names
)

df["HousePrice"] = housing.target

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,HousePrice
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [98]:
print("Number of rows and columns:", df.shape)

Number of rows and columns: (20640, 9)

In [99]:
X = housing.data
y = housing.target

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (20640, 8)
Target shape: (20640,)

In [100]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)
print("Training targets:", y_train.shape)
print("Testing targets:", y_test.shape)

Training features: (16512, 8)
Testing features: (4128, 8)
Training targets: (16512,)
Testing targets: (4128,)

In [101]:
model = LinearRegression()

In [102]:
model.fit(X_train, y_train)

LinearRegression()

In [103]:
y_pred = model.predict(X_test)

print("Predicted House Prices:")
print(y_pred[:10])

Predicted House Prices:
[0.71912284 1.76401657 2.70965883 2.83892593 2.60465725 2.01175367
 2.64550005 2.16875532 2.74074644 3.91561473]

In [104]:
mse = mean_squared_error(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.5558915986952422

In [105]:
r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

R² Score: 0.5757877060324524

In [106]:
print("Model Performance")
print("------------------")
print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Model Performance
------------------
Mean Squared Error (MSE): 0.5558915986952422
R² Score: 0.5757877060324524

# Task 2: Diabetes Progression Prediction Model

In [107]:
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()

In [108]:
df_diabetes = pd.DataFrame(
    diabetes.data,
    columns=diabetes.feature_names
)

df_diabetes["DiseaseProgression"] = diabetes.target

df_diabetes.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,DiseaseProgression
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [109]:
print("Dataset Shape:", df_diabetes.shape)

Dataset Shape: (442, 11)

In [110]:
X = diabetes.data
y = diabetes.target

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (442, 10)
Target Shape: (442,)

In [111]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Target:", y_train.shape)
print("Testing Target:", y_test.shape)

Training Features: (353, 10)
Testing Features: (89, 10)
Training Target: (353,)
Testing Target: (89,)

In [112]:
model = LinearRegression()

In [113]:
model.fit(X_train, y_train)

LinearRegression()

In [114]:
y_pred = model.predict(X_test)

print("Predicted Disease Progression:")
print(y_pred[:10])

Predicted Disease Progression:
[139.5475584  179.51720835 134.03875572 291.41702925 123.78965872
  92.1723465  258.23238899 181.33732057  90.22411311 108.63375858]

In [115]:
mse = mean_squared_error(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 2900.193628493482

In [116]:
r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

R² Score: 0.4526027629719195

In [117]:
print("Diabetes Regression Model Performance")
print("--------------------------------------")
print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Diabetes Regression Model Performance
--------------------------------------
Mean Squared Error (MSE): 2900.193628493482
R² Score: 0.4526027629719195